### ISSUE TITLE
Consider using a static variable instead of INJECTED for infinite-loop prevention

### ISSUE THREAD

**Issue by gedankenexperimenter** [gedankenlab/Kaleidoscope-Qukeys#18]
If we use an INJECTED event, other plugins might ignore a keypress we want them to process.

**Comment by gedankenexperimenter** [comment]
I just had a look at [Kaleidoscope-Leader](https://github.com/keyboardio/Kaleidoscope-Leader), and I'm now convinced that this is necessary. That plugin — and I'm sure it's not the only one — ignores events with a `keyswitch_state` flagged `INJECTED`, so we need to use a different mechanism in order for those plugins to receive keypresses.

**Comment by pdcawley** [comment]
It seems to me that a simple boolean INJECTED flag isn't going to cut it. Need to hang some information about what injected the key, so plugins can ignore stuff that they injected, but treat keys injected by other plugins as 'real'.

**Comment by gedankenexperimenter** [comment]
That's essentially what I'm proposing, but it's not necessary to pass the information as a hook function parameter; a plugin that calls `handleKeyswitchEvent()` can set a variable just before that to tell it to ignore key events until that flag is cleared, and clear the flag instead of acting on that event.
