### ISSUE TITLE
ShiftToLayer(FUNCTION) is permanent

### ISSUE THREAD

**Issue by florentnicoulaud** [gedankenlab/Kaleidoscope-Qukeys#31]
Hi,

I have a new issue occurring since the February 1st commit (0fa876f).
When I press my 'Fn' key, which does: ShiftToLayer(FUNCTION), I am further locked onto that layer.
I can confirm that up to the previous commit (january 31st : f6f5f9a) the issue does not occur.
I'd be glad to help if you have any question to find and correct the bug.
Meanwhile, I'm using the f6f5f9a version.

Cheers!

**Comment by gedankenexperimenter** [comment]
I just committed a fix for that! If the newest version isn't working, let me know.

**Comment by florentnicoulaud** [comment]
Great! I'll test that tomorrow and confirm the fix.

**Comment by florentnicoulaud** [comment]
Problem solved, thanks !
