### ISSUE TITLE
Can't build Qukeys

### ISSUE THREAD

**Issue by sinkr** [gedankenlab/Kaleidoscope-Qukeys#33]
Simply including 

#include <Kaleidoscope-Qukeys.h>

causes my builds to fail like so:

`Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp: In static member function 'static int8_t kaleidoscope::Qukeys::lookupQukey(uint8_t)':
/Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp:96:37: error: 'class Layer_' has no member named 'lookupActiveLayer'
           (qukeys[i].layer == Layer.lookupActiveLayer(row, col))) {
                                     ^
/Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp: In static member function 'static void kaleidoscope::Qukeys::flushKey(bool, uint8_t)':
/Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp:153:39: error: 'class Keyboard_' has no member named 'keyReport'
   memcpy(hid_report.allkeys, Keyboard.keyReport.allkeys, sizeof(hid_report));
                                       ^
/Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp:155:19: error: 'class Keyboard_' has no member named 'keyReport'
   memcpy(Keyboard.keyReport.allkeys, Keyboard.lastKeyReport.allkeys, sizeof(Keyboard.keyReport));
                   ^
/Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp:155:47: error: 'class Keyboard_' has no member named 'lastKeyReport'
   memcpy(Keyboard.keyReport.allkeys, Keyboard.lastKeyReport.allkeys, sizeof(Keyboard.keyReport));
                                               ^
/Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp:155:86: error: 'class Keyboard_' has no member named 'keyReport'
Multiple libraries were found for "HID.h"
 Used: /Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/HID
   memcpy(Keyboard.keyReport.allkeys, Keyboard.lastKeyReport.allkeys, sizeof(Keyboard.keyReport));
 Not used: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/HID
                                                                                      ^
/Users/robert/Library/Arduino15/packages/keyboardio/hardware/avr/1.22.0/libraries/Kaleidoscope-Qukeys/src/Kaleidoscope/Qukeys.cpp:166:19: error: 'class Keyboard_' has no member named 'keyReport'
   memcpy(Keyboard.keyReport.allkeys, hid_report.allkeys, sizeof(hid_report));
                   ^
exit status 1
Error compiling for board Keyboardio Model 01.`

Any ideas?

**Comment by gedankenexperimenter** [comment]
I think you're probably using an older version of Kaleidoscope than what Qukeys requires. If you check out the latest version of the keyboardio/Arduino-Boards repository from GitHub, and use that, you should be able to build Qukeys. I'm not sure, but you might also need to remove the one installed by the Arduino boards-manager.

**Comment by sinkr** [comment]
Ah, thank you--still new to this.

Regards,

-R.

**Comment by gedankenexperimenter** [comment]
This seems to be resolved, so I'm closing this issue.
