### ISSUE TITLE
What are the first three arguments of the function?

### ISSUE THREAD

**Issue by hoschi** [gedankenlab/Kaleidoscope-Qukeys#38]
What are the first three arguments of the function?

```
kaleidoscope::Qukey(0, 2, 1, Key_LeftGui),      // A/cmd
```

**Comment by gedankenexperimenter** [comment]
The first one is the layer number (e.g. `QWERTY`).

The next two are the row number and column number — same as R1C1 notation used in the keymap. Row 0 is at the top, column 0 is on the left. Thumb keys are columns 7 & 8, and palm keys are R3C6 & R3C9. It's not great, but it does fully specify a keymap position.
